## Basic Fundamental Operations using Tensors

In [1]:
import tensorflow as tf
import numpy as np

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


### 1. Creating Tensors

In [2]:
# Creating tensors of different dimensions
# 1D Tensor (Vector)
tensor_1d = tf.constant([1, 2, 3, 4, 5])
print("1D Tensor:", tensor_1d)
print("Shape:", tensor_1d.shape)
print("Rank:", tf.rank(tensor_1d).numpy())

# 2D Tensor (Matrix)
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])
print("\n2D Tensor:\n", tensor_2d)
print("Shape:", tensor_2d.shape)
print("Rank:", tf.rank(tensor_2d).numpy())

# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Tensor:\n", tensor_3d)
print("Shape:", tensor_3d.shape)
print("Rank:", tf.rank(tensor_3d).numpy())

# 4D Tensor
tensor_4d = tf.random.normal([2, 3, 4, 5])
print("\n4D Tensor shape:", tensor_4d.shape)
print("Rank:", tf.rank(tensor_4d).numpy())

# Special tensors
zeros = tf.zeros([3, 3])
ones = tf.ones([2, 4])
random = tf.random.normal([3, 3])
range_tensor = tf.range(0, 10, 2)

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nRandom:\n", random)
print("\nRange:", range_tensor)

1D Tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Shape: (5,)
Rank: 1

2D Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Rank: 2

3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2)
Rank: 3

4D Tensor shape: (2, 3, 4, 5)
Rank: 4

Zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)

Ones:
 tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)

Random:
 tf.Tensor(
[[ 0.86209244  0.7580136   0.942517  ]
 [ 0.36195517 -0.1641336  -0.66196865]
 [-0.16825125 -0.50829244  0.05707361]], shape=(3, 3), dtype=float32)

Range: tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


### 2. Tensor Rank Operations

In [3]:
# Rank (number of dimensions) of tensors
print("Rank of 1D tensor:", tf.rank(tensor_1d).numpy())
print("Rank of 2D tensor:", tf.rank(tensor_2d).numpy())
print("Rank of 3D tensor:", tf.rank(tensor_3d).numpy())
print("Rank of 4D tensor:", tf.rank(tensor_4d).numpy())

# Alternative: using ndim
print("\nUsing ndim attribute:")
print("Rank of 1D tensor:", tensor_1d.ndim)
print("Rank of 2D tensor:", tensor_2d.ndim)
print("Rank of 3D tensor:", tensor_3d.ndim)
print("Rank of 4D tensor:", tensor_4d.ndim)

# Getting detailed information
print("\n1D Tensor - Rank:", tf.rank(tensor_1d).numpy(), "Shape:", tensor_1d.shape, "Size:", tf.size(tensor_1d).numpy())
print("2D Tensor - Rank:", tf.rank(tensor_2d).numpy(), "Shape:", tensor_2d.shape, "Size:", tf.size(tensor_2d).numpy())
print("3D Tensor - Rank:", tf.rank(tensor_3d).numpy(), "Shape:", tensor_3d.shape, "Size:", tf.size(tensor_3d).numpy())
print("4D Tensor - Rank:", tf.rank(tensor_4d).numpy(), "Shape:", tensor_4d.shape, "Size:", tf.size(tensor_4d).numpy())

Rank of 1D tensor: 1
Rank of 2D tensor: 2
Rank of 3D tensor: 3
Rank of 4D tensor: 4

Using ndim attribute:
Rank of 1D tensor: 1
Rank of 2D tensor: 2
Rank of 3D tensor: 3
Rank of 4D tensor: 4

1D Tensor - Rank: 1 Shape: (5,) Size: 5
2D Tensor - Rank: 2 Shape: (2, 3) Size: 6
3D Tensor - Rank: 3 Shape: (2, 2, 2) Size: 8
4D Tensor - Rank: 4 Shape: (2, 3, 4, 5) Size: 120


### 3. Basic Arithmetic Operations

In [4]:
# Create sample tensors
a = tf.constant([1.0, 2.0, 3.0, 4.0])
b = tf.constant([5.0, 6.0, 7.0, 8.0])

# Addition
print("Addition:", tf.add(a, b))
print("Using +:", a + b)

# Subtraction
print("\nSubtraction:", tf.subtract(a, b))
print("Using -:", a - b)

# Multiplication (element-wise)
print("\nElement-wise multiplication:", tf.multiply(a, b))
print("Using *:", a * b)

# Division
print("\nDivision:", tf.divide(a, b))
print("Using /:", a / b)

# Power
print("\nPower (a^2):", tf.pow(a, 2))
print("Using **:", a ** 2)

# Matrix multiplication for 2D tensors
matrix_a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
matrix_b = tf.constant([[5.0, 6.0], [7.0, 8.0]])
print("\nMatrix multiplication:")
print(tf.matmul(matrix_a, matrix_b))
print("Using @ operator:")
print(matrix_a @ matrix_b)

Addition: tf.Tensor([ 6.  8. 10. 12.], shape=(4,), dtype=float32)
Using +: tf.Tensor([ 6.  8. 10. 12.], shape=(4,), dtype=float32)

Subtraction: tf.Tensor([-4. -4. -4. -4.], shape=(4,), dtype=float32)
Using -: tf.Tensor([-4. -4. -4. -4.], shape=(4,), dtype=float32)

Element-wise multiplication: tf.Tensor([ 5. 12. 21. 32.], shape=(4,), dtype=float32)
Using *: tf.Tensor([ 5. 12. 21. 32.], shape=(4,), dtype=float32)

Division: tf.Tensor([0.2        0.33333334 0.42857143 0.5       ], shape=(4,), dtype=float32)
Using /: tf.Tensor([0.2        0.33333334 0.42857143 0.5       ], shape=(4,), dtype=float32)

Power (a^2): tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)
Using **: tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)

Matrix multiplication:
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Using @ operator:
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


### 4. Diff Operations on 1D Tensors

In [5]:
# 1D Tensor Diff - calculates differences between adjacent elements
tensor_1d_diff = tf.constant([1.0, 3.0, 6.0, 10.0, 15.0])
print("Original 1D tensor:", tensor_1d_diff)
print("Shape:", tensor_1d_diff.shape)
print("Rank:", tf.rank(tensor_1d_diff).numpy())

# First order difference
# TensorFlow doesn't have built-in diff, so we use slicing
diff_1 = tensor_1d_diff[1:] - tensor_1d_diff[:-1]
print("\n1st order diff:", diff_1)
print("Shape:", diff_1.shape)

# Second order difference
diff_2 = diff_1[1:] - diff_1[:-1]
print("\n2nd order diff:", diff_2)
print("Shape:", diff_2.shape)

# Different example
x = tf.constant([1.0, 4.0, 9.0, 16.0, 25.0])
print("\n\nAnother example:")
print("Original:", x)
diff_x = x[1:] - x[:-1]
print("1st diff:", diff_x)
print("Interpretation: differences are [3, 5, 7, 9]")

Original 1D tensor: tf.Tensor([ 1.  3.  6. 10. 15.], shape=(5,), dtype=float32)
Shape: (5,)
Rank: 1

1st order diff: tf.Tensor([2. 3. 4. 5.], shape=(4,), dtype=float32)
Shape: (4,)

2nd order diff: tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
Shape: (3,)


Another example:
Original: tf.Tensor([ 1.  4.  9. 16. 25.], shape=(5,), dtype=float32)
1st diff: tf.Tensor([3. 5. 7. 9.], shape=(4,), dtype=float32)
Interpretation: differences are [3, 5, 7, 9]


### 5. Diff Operations on 2D Tensors

In [6]:
# 2D Tensor Diff
tensor_2d_diff = tf.constant([[1.0, 3.0, 6.0, 10.0],
                               [2.0, 5.0, 9.0, 14.0],
                               [3.0, 7.0, 12.0, 18.0]])
print("Original 2D tensor:")
print(tensor_2d_diff)
print("Shape:", tensor_2d_diff.shape)
print("Rank:", tf.rank(tensor_2d_diff).numpy())

# Diff along dimension 0 (rows)
diff_dim0 = tensor_2d_diff[1:, :] - tensor_2d_diff[:-1, :]
print("\nDiff along dimension 0 (row-wise):")
print(diff_dim0)
print("Shape:", diff_dim0.shape)

# Diff along dimension 1 (columns)
diff_dim1 = tensor_2d_diff[:, 1:] - tensor_2d_diff[:, :-1]
print("\nDiff along dimension 1 (column-wise):")
print(diff_dim1)
print("Shape:", diff_dim1.shape)

# Second order diff along dimension 1
first_diff = tensor_2d_diff[:, 1:] - tensor_2d_diff[:, :-1]
diff_2nd = first_diff[:, 1:] - first_diff[:, :-1]
print("\n2nd order diff along dimension 1:")
print(diff_2nd)
print("Shape:", diff_2nd.shape)

Original 2D tensor:
tf.Tensor(
[[ 1.  3.  6. 10.]
 [ 2.  5.  9. 14.]
 [ 3.  7. 12. 18.]], shape=(3, 4), dtype=float32)
Shape: (3, 4)
Rank: 2

Diff along dimension 0 (row-wise):
tf.Tensor(
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]], shape=(2, 4), dtype=float32)
Shape: (2, 4)

Diff along dimension 1 (column-wise):
tf.Tensor(
[[2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]], shape=(3, 3), dtype=float32)
Shape: (3, 3)

2nd order diff along dimension 1:
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
Shape: (3, 2)


### 6. Diff Operations on 3D Tensors

In [7]:
# 3D Tensor Diff
tensor_3d_diff = tf.reshape(tf.range(24, dtype=tf.float32), [2, 3, 4])
print("Original 3D tensor:")
print(tensor_3d_diff)
print("Shape:", tensor_3d_diff.shape)
print("Rank:", tf.rank(tensor_3d_diff).numpy())

# Diff along dimension 0
diff_3d_dim0 = tensor_3d_diff[1:, :, :] - tensor_3d_diff[:-1, :, :]
print("\nDiff along dimension 0:")
print(diff_3d_dim0)
print("Shape:", diff_3d_dim0.shape)

# Diff along dimension 1
diff_3d_dim1 = tensor_3d_diff[:, 1:, :] - tensor_3d_diff[:, :-1, :]
print("\nDiff along dimension 1:")
print(diff_3d_dim1)
print("Shape:", diff_3d_dim1.shape)

# Diff along dimension 2
diff_3d_dim2 = tensor_3d_diff[:, :, 1:] - tensor_3d_diff[:, :, :-1]
print("\nDiff along dimension 2:")
print(diff_3d_dim2)
print("Shape:", diff_3d_dim2.shape)

Original 3D tensor:
tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]], shape=(2, 3, 4), dtype=float32)
Shape: (2, 3, 4)
Rank: 3

Diff along dimension 0:
tf.Tensor(
[[[12. 12. 12. 12.]
  [12. 12. 12. 12.]
  [12. 12. 12. 12.]]], shape=(1, 3, 4), dtype=float32)
Shape: (1, 3, 4)

Diff along dimension 1:
tf.Tensor(
[[[4. 4. 4. 4.]
  [4. 4. 4. 4.]]

 [[4. 4. 4. 4.]
  [4. 4. 4. 4.]]], shape=(2, 2, 4), dtype=float32)
Shape: (2, 2, 4)

Diff along dimension 2:
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)
Shape: (2, 3, 3)


### 7. Diff Operations on 4D Tensors

In [8]:
# 4D Tensor Diff (common in deep learning: batch_size, channels, height, width)
tensor_4d_diff = tf.reshape(tf.range(120, dtype=tf.float32), [2, 3, 4, 5])
print("Original 4D tensor shape:", tensor_4d_diff.shape)
print("Rank:", tf.rank(tensor_4d_diff).numpy())
print("\nFirst slice of 4D tensor:")
print(tensor_4d_diff[0, 0, :, :])

# Diff along different dimensions
diff_4d_dim0 = tensor_4d_diff[1:, :, :, :] - tensor_4d_diff[:-1, :, :, :]
diff_4d_dim1 = tensor_4d_diff[:, 1:, :, :] - tensor_4d_diff[:, :-1, :, :]
diff_4d_dim2 = tensor_4d_diff[:, :, 1:, :] - tensor_4d_diff[:, :, :-1, :]
diff_4d_dim3 = tensor_4d_diff[:, :, :, 1:] - tensor_4d_diff[:, :, :, :-1]

print("\nDiff along dimension 0 (batch):", diff_4d_dim0.shape)
print("Diff along dimension 1 (channels):", diff_4d_dim1.shape)
print("Diff along dimension 2 (height):", diff_4d_dim2.shape)
print("Diff along dimension 3 (width):", diff_4d_dim3.shape)

# Example: diff along the last dimension
print("\nDiff along last dimension (width):")
print("First slice result:")
print(diff_4d_dim3[0, 0, :, :])

Original 4D tensor shape: (2, 3, 4, 5)
Rank: 4

First slice of 4D tensor:
tf.Tensor(
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]], shape=(4, 5), dtype=float32)

Diff along dimension 0 (batch): (1, 3, 4, 5)
Diff along dimension 1 (channels): (2, 2, 4, 5)
Diff along dimension 2 (height): (2, 3, 3, 5)
Diff along dimension 3 (width): (2, 3, 4, 4)

Diff along last dimension (width):
First slice result:
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


### 8. Reshaping Operations

In [9]:
# Reshaping tensors
x = tf.range(12)
print("Original 1D tensor:", x)
print("Shape:", x.shape)

# Reshape to 2D
x_2d = tf.reshape(x, [3, 4])
print("\nReshaped to 3x4:")
print(x_2d)

# Reshape to 3D
x_3d = tf.reshape(x, [2, 2, 3])
print("\nReshaped to 2x2x3:")
print(x_3d)

# Reshape with -1 (automatic dimension calculation)
x_auto = tf.reshape(x, [4, -1])
print("\nReshape with -1 (4x-1 becomes 4x3):")
print(x_auto)

# Flatten
x_flat = tf.reshape(x_2d, [-1])
print("\nFlattened:", x_flat)

# Expand dimensions
x_expanded = tf.expand_dims(x, axis=0)
print("\nExpanded dimensions (add batch):", x_expanded.shape)

# Squeeze (remove dimensions of size 1)
x_squeezable = tf.constant([[[1, 2, 3, 4]]])
print("\nOriginal shape:", x_squeezable.shape)
print("After squeeze:", tf.squeeze(x_squeezable).shape)

Original 1D tensor: tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
Shape: (12,)

Reshaped to 3x4:
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)

Reshaped to 2x2x3:
tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]], shape=(2, 2, 3), dtype=int32)

Reshape with -1 (4x-1 becomes 4x3):
tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)

Flattened: tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)

Expanded dimensions (add batch): (1, 12)

Original shape: (1, 1, 4)
After squeeze: (4,)


### 9. Indexing and Slicing

In [10]:
# Indexing and slicing
tensor = tf.reshape(tf.range(20), [4, 5])
print("Original tensor:")
print(tensor)

# Basic indexing
print("\nFirst row:", tensor[0])
print("Element at [2, 3]:", tensor[2, 3])

# Slicing
print("\nFirst 2 rows:")
print(tensor[:2])
print("\nLast 2 columns:")
print(tensor[:, -2:])
print("\nEvery other row:")
print(tensor[::2])

# Advanced indexing with gather
print("\nRows 1 and 3:")
print(tf.gather(tensor, [1, 3]))

# Boolean indexing
mask = tensor > 10
print("\nMask (elements > 10):")
print(mask)
print("Elements > 10:", tf.boolean_mask(tensor, mask))

Original tensor:
tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]], shape=(4, 5), dtype=int32)

First row: tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
Element at [2, 3]: tf.Tensor(13, shape=(), dtype=int32)

First 2 rows:
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)

Last 2 columns:
tf.Tensor(
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]], shape=(4, 2), dtype=int32)

Every other row:
tf.Tensor(
[[ 0  1  2  3  4]
 [10 11 12 13 14]], shape=(2, 5), dtype=int32)

Rows 1 and 3:
tf.Tensor(
[[ 5  6  7  8  9]
 [15 16 17 18 19]], shape=(2, 5), dtype=int32)

Mask (elements > 10):
tf.Tensor(
[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]], shape=(4, 5), dtype=bool)
Elements > 10: tf.Tensor([11 12 13 14 15 16 17 18 19], shape=(9,), dtype=int32)


### 10. Aggregation Operations

In [11]:
# Aggregation operations
data = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
print("Original tensor:")
print(data)

# Sum
print("\nSum of all elements:", tf.reduce_sum(data))
print("Sum along axis 0 (columns):", tf.reduce_sum(data, axis=0))
print("Sum along axis 1 (rows):", tf.reduce_sum(data, axis=1))

# Mean
print("\nMean of all elements:", tf.reduce_mean(data))
print("Mean along axis 0:", tf.reduce_mean(data, axis=0))
print("Mean along axis 1:", tf.reduce_mean(data, axis=1))

# Max and Min
print("\nMax value:", tf.reduce_max(data))
print("Min value:", tf.reduce_min(data))
print("Max along axis 0:", tf.reduce_max(data, axis=0))
print("Argmax (index of max):", tf.argmax(tf.reshape(data, [-1])))

# Standard deviation and variance
print("\nStandard deviation:", tf.math.reduce_std(data))
print("Variance:", tf.math.reduce_variance(data))

Original tensor:
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)

Sum of all elements: tf.Tensor(45.0, shape=(), dtype=float32)
Sum along axis 0 (columns): tf.Tensor([12. 15. 18.], shape=(3,), dtype=float32)
Sum along axis 1 (rows): tf.Tensor([ 6. 15. 24.], shape=(3,), dtype=float32)

Mean of all elements: tf.Tensor(5.0, shape=(), dtype=float32)
Mean along axis 0: tf.Tensor([4. 5. 6.], shape=(3,), dtype=float32)
Mean along axis 1: tf.Tensor([2. 5. 8.], shape=(3,), dtype=float32)

Max value: tf.Tensor(9.0, shape=(), dtype=float32)
Min value: tf.Tensor(1.0, shape=(), dtype=float32)
Max along axis 0: tf.Tensor([7. 8. 9.], shape=(3,), dtype=float32)
Argmax (index of max): tf.Tensor(8, shape=(), dtype=int64)

Standard deviation: tf.Tensor(2.5819888, shape=(), dtype=float32)
Variance: tf.Tensor(6.6666665, shape=(), dtype=float32)


### 11. Concatenation and Stacking

In [12]:
# Concatenation and stacking
t1 = tf.constant([[1, 2], [3, 4]])
t2 = tf.constant([[5, 6], [7, 8]])

print("Tensor 1:")
print(t1)
print("\nTensor 2:")
print(t2)

# Concatenate
print("\nConcatenate along axis 0 (vertical):")
print(tf.concat([t1, t2], axis=0))

print("\nConcatenate along axis 1 (horizontal):")
print(tf.concat([t1, t2], axis=1))

# Stack (creates new dimension)
print("\nStack along axis 0:")
stacked_0 = tf.stack([t1, t2], axis=0)
print(stacked_0)
print("Shape:", stacked_0.shape)

print("\nStack along axis 1:")
stacked_1 = tf.stack([t1, t2], axis=1)
print(stacked_1)
print("Shape:", stacked_1.shape)

Tensor 1:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Tensor 2:
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)

Concatenate along axis 0 (vertical):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)

Concatenate along axis 1 (horizontal):
tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)

Stack along axis 0:
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2)

Stack along axis 1:
tf.Tensor(
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2)


### 12. Summary: Rank and Shape across Different Tensors

In [13]:
# Summary of rank and shapes
tensors_dict = {
    "Scalar (0D)": tf.constant(42),
    "Vector (1D)": tf.constant([1, 2, 3, 4, 5]),
    "Matrix (2D)": tf.random.normal([3, 4]),
    "3D Tensor": tf.random.normal([2, 3, 4]),
    "4D Tensor": tf.random.normal([2, 3, 4, 5]),
    "5D Tensor": tf.random.normal([2, 3, 4, 5, 6])
}

print("=" * 70)
print(f"{'Tensor Type':<20} {'Rank':<10} {'Shape':<25} {'Total Elements':<15}")
print("=" * 70)

for name, tensor in tensors_dict.items():
    rank = tf.rank(tensor).numpy()
    shape = str(tuple(tensor.shape.as_list()))
    numel = tf.size(tensor).numpy()
    print(f"{name:<20} {rank:<10} {shape:<25} {numel:<15}")

print("=" * 70)

Tensor Type          Rank       Shape                     Total Elements 
Scalar (0D)          0          ()                        1              
Vector (1D)          1          (5,)                      5              
Matrix (2D)          2          (3, 4)                    12             
3D Tensor            3          (2, 3, 4)                 24             
4D Tensor            4          (2, 3, 4, 5)              120            
5D Tensor            5          (2, 3, 4, 5, 6)           720            
